services:
  axios-calc:
    build: .
    container_name: axios-calc
    restart: unless-stopped
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.axios-calc.rule=Host(`axioscalc.sgdev.cloud`)"
      - "traefik.http.routers.axios-calc.entrypoints=websecure"
      - "traefik.http.routers.axios-calc.tls.certresolver=meuresolver"
      - "traefik.http.services.axios-calc.loadbalancer.server.port=3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "file:/app/data/prod.db"
      NODE_ENV: "production"
    volumes:
      - ./data:/app/data
networks:
  public:
    external: true